activities = [
    "Acheteur d’espaces publicitaires", "Acheteur en centrale d’achat", "Acheteur en produits agroalimentaires", 
    "Acheteur en produits horticoles", "Acheteur industriel", "Acousticien", "Acteur", "Actrice", "Actuaire", 
    "Administrateur dans la Fonction publique européenne", "Administrateur de base de données", 
    "Administrateur de réseaux", "Administrateur des ventes", "Administrateur réseaux", "Agent", 
    "Agent d'accueil en office de tourisme", "Agent d’accueil", "Agent de développement local", 
    "Agent de planning aérien (ou agent de planification)", "Agent de recouvrement du Trésor", "Agent général", 
    "Agent immobilier", "Agriculteur / Paysan", "Aide médico-psychologique", "Aide-soignant(e)", 
    "Aiguilleur du ciel", "Ambassadeur ou consul", "Analyste de crédit", "Analyste social", "Anesthésiste-réanimateur", 
    "Animateur de formation", "Animateur de patrimoine", "Animateur des activités physiques", "Animateur nature", 
    "Animateur radio-télé", "Animateur socioculturel", "Animateur sportif", "Animateur touristique", 
    "Aquaculteur", "Archéologue", "Architecte", "Architecte d’intérieur", "Architecte en systèmes d’information", 
    "Assistant comptable", "Assistant export", "Assistant(e) de service social", "Astronome (ou astrophysicien)", 
    "Attaché commercial", "Attaché de presse", "Audioprothésiste", "Auditeur financier", "Auxiliaire de puériculture", 
    "Avocat", "Avocat", "Bibliothécaire", "Bibliothécaire jeunesse", "Biochimiste", "Biologiste", "Biologiste médical", 
    "Biostatisticien", "Botaniste", "Campus manager", "Cartographe", "Céramiste", "Chargé d’affaires", 
    "Chargé d’études commerciales", "Chargé de clientèle dans la banque", "Chargé de clientèle en assurance", 
    "Chargé de communication événementielle", "Chargé de pharmaco-vigilance", "Chargé des relations publiques", 
    "Chargé du recrutement", "Chargé du suivi des programmes humanitaires", "Chef d'escale", "Chef de cabine", 
    "Chef de caisse", "Chef de chantier", "Chef de mission dans l’humanitaire", "Chef de produit", "Chef de projet urbain", 
    "Chef de pub en agence", "Chef de rang", "Chef de rayon", "Chef opérateur", "Chef réceptionniste", 
    "Chercheur en sciences et en industries", "Chirurgien dentiste", "Clown", "Com and Ben", "Commandant de bord", 
    "Commissaire de police", "Commissaire-priseur", "Concepteur-rédacteur", "Conducteur de travaux", 
    "Conférencier de musée et de monument", "Conseil en lobbying", "Conseiller agricole", "Conseiller conjugal et familial", 
    "Conseiller d'orientation-psychologue", "Conseiller en agriculture durable", "Conseiller en économie sociale et familiale", 
    "Conseiller en environnement", "Conseiller en immobilier d’entreprise", "Conseiller en management", 
    "Conseiller en organisation", "Conseiller principal d'éducation", "Conseiller-vendeur en agence de voyages", 
    "Conservateur de musée", "Consultant en recrutement", "Conteur", "Contrôleur budgétaire", "Contrôleur de gestion", 
    "Costumier", "Courtier", "Créateur de parfums", "Décorateur-scénographe", "Designer industriel", "Designer sonore", 
    "Designer textile", "Dessinateur industriel", "Développeur de produits bancaires", "Diététicien", "Directeur artistique", 
    "Directeur d'établissement", "Directeur d'une salle de spectacle", "Directeur d’enseigne", 
    "Directeur de centre de vacances ou de loisris", "Directeur de création", "Directeur des achats", "Directeur des opérations", 
    "Directeur des ressources humaines", "Documentaliste de CDI", "Ebéniste", "Économe", "Économiste de la construction", 
    "Ecotoxicologue", "Editeur", "Éducateur de jeunes enfants", "Éducateur de la Protection judiciaire de la jeunesse", 
    "Educateur spécialisé", "Educateur technique spécialisé", "Educatrice de jeunes enfants", "Educatrice spécialisée", 
    "Électrotechnicien", "Enseignant à l'étranger", "Enseignant chercheur", "Entraîneur", "Ethnologue", "Éthologiste", 
    "Expert automobile", "Expert immobilier", "Expert incendies et risques divers", "Expert-comptable", "Facteur", "Game designer", 
    "Généticien", "Géologue", "Géomètre-topographe", "Gestionnaire de carrière", "Gestionnaire de paie", 
    "Gestionnaire de patrimoine", "Graphiste multimédia", "Guide accompagnateur", "Guide interprète", "Gynécologue", 
    "Herboriste", "Horticulteur", "Hôtesse de l'air ou steward", "Hydrogéologue", "Iconographe", "Illustrateur", 
    "Infirmier", "Infirmier d’entreprise", "Infirmier sapeur-pompier", "Infirmière", "Infographiste de presse", "Ingénieur informaticien", 
    "Ingénieur automatisme-instrumentation", "Ingénieur calcul et appui scientifique", "Ingénieur chimiste", 
    "Ingénieur d'études dans l'automobile", "Ingénieur d’études dans l'industrie", "Ingénieur d’études en aéronautique", 
    "Ingénieur de fabrication", "Ingénieur du son", "Ingénieur en environnement", "Ingénieur en mécanique", 
    "Ingénieur en recherche clinique", "Ingénieur méthodes", "Ingénieur numéricien", "Ingénieur procédés", 
    "Ingénieur qualité ou qualiticien", "Ingénieur télécoms", "Inspecteur comptable", "Inspecteur des Finances", 
    "Inspecteur des impôts", "Inspecteur du travail", "Interprète", "Journaliste", "Journaliste d’entreprise", 
    "Journaliste radio en studio", "Journaliste reporter d’images (JRI)", "Juge aux affaires familiales", 
    "Juge d'application des peines (JAP)", "Juge des enfants", "Libraire", "Lieutenant de police", "Lieutenant de pompiers", 
    "Logisticien", "Logisticien dans l'humanitaire", "Ludothécaire", "Maître d’hôtel", "Maître nageur sauveteur", 
    "Manager dans la restauration rapide", "Manipulateur en électroradiologie", "Maquettiste", "Marionnettiste", 
    "Masseur-kinésithérapeute", "Médecin du travail", "Médecin généraliste", "Médecin légiste", "Médecin scolaire", 
    "Média-planneur", "Médiateur", "Médiateur culturel", "Merchandiser", "Metteur en scène", "Microtechnicien", 
    "Modéliste", "Moniteur de ski", "Moniteur-éducateur", "Muséographe", "Neurologue", "Notaire", "Océanologue", 
    "Officier de l’armée de l’air", "Officier de la marine marchande", "Officier marinier ou officier de la Marine nationale", 
    "Opérateur back office", "Opérateur de marché en CO2", "Opérateur middle office", "Ophtalmologue", "Opticien-lunetier", 
    "Ornithologue", "Orthophoniste", "Orthoprothésiste", "Orthoptiste", "Ostéopathe", "Oto-rhino-laryngologiste", 
    "Paysagiste", "Pédiatre", "Pédicure-podologue", "Pédologue", "Pédopsychiatre", "Pharmacien d'officine", "Photographe", 
    "Pilote d’hélicoptère", "Pilote de ligne", "Producteur télé", "Professeur agrégé", 
    "Professeur d’EPS (Éducation physique et sportive)", "Professeur de lycée professionnel", "Professeur des écoles", 
    "Professeur des écoles spécialisées", "Professeur en collège ou en lycée", "Prothésiste dentaire", "Psychanalyste", 
    "Psychiatre", "Psychologue scolaire", "Psychomotricien", "Puéricultrice", "Réalisateur", "Reporter", "Reporter radio", 
    "Responsable d’ordonnancement", "Responsable de bases de données", "Responsable de formation", 
    "Responsable de la communication interne", "Responsable de la promotion des ventes", "Responsable de relais assistantes maternelles", 
    "Responsable du marketing direct", "Responsable HSE (hygiène-sécurité-environnement)", "Responsable SAV (Service après-vente)", 
    "Restaurateur d’œuvres d’art", "Restaurateur de livres anciens", "Sage-femme", "Scénariste", "Scénariste", "Scripte", 
    "Secrétaire administratif ou de chancellerie", "Secrétaire aux Affaires étrangères", "Sociologue", "Spécialiste en biotechnologies", 
    "Sportif professionnel", "Statisticien", "Styliste", "Technicien conseiller en agrobiologie", "Technicien d'analyses biomédicales", 
    "Technicien de maintenance", "Technicien de mesure de la pollution", "Technicien du génie rural", "Technicien en automatismes", 
    "Technicien paysagiste", "Technicien traitement des eaux", "Technico-commercial", "Technico-commercial en agrofournitures", 
    "Testeur", "Trader", "Traducteur", "Urbaniste", "Vendeur automobile", "Vendeur d’espaces publicitaires", "Vétérinaire", 
    "Visiteur médical", "Viticulteur", "Volcanologue", "Webmaster", "Zoologiste"                             
];
