colors =
[
    {"v": "Abricot", "color": "#E67E30"},
    {"v": "Absinthe", "color": "#7FDD4C"},
    {"v": "Acajou", "color": "#88421D"},
    {"v": "Aigue-marine", "color": "#79F8F8"},
    {"v": "Albâtre", "color": "#FEFEFE"},
    {"v": "Alezan (chevaux)", "color": "#A76726"},
    {"v": "Amande", "color": "#82C46C"},
    {"v": "Amarante", "color": "#91283B"},
    {"v": "Ambre jaune", "color": "#F0C300"},
    {"v": "Ambre rouge", "color": "#AD390E"},
    {"v": "Améthyste", "color": "#884DA7"},
    {"v": "Anthracite", "color": "#303030"},
    {"v": "Aquilain (chevaux)", "color": "#AD4F09"},
    {"v": "Ardoise", "color": "#5A5E6B"},
    {"v": "Argent", "color": "#CECECE"},
    {"v": "Argent (héraldique)", "color": "#FFFFFF"},
    {"v": "Argile", "color": "#EFEFEF"},
    {"v": "Asperge", "color": "#7BA05B"},
    {"v": "Aubergine", "color": "#370028"},
    {"v": "Auburn (cheveux)", "color": "#9D3E0C"},
    {"v": "Aurore", "color": "#FFCB60"},
    {"v": "Avocat", "color": "#568203"},
    {"v": "Azur", "color": "#007FFF"},
    {"v": "Azur (héraldique)", "color": "#1E7FCB"},
    {"v": "Azur brume", "color": "#F0FFFF"},
    {"v": "Azur clair", "color": "#74D0F1"},
    {"v": "Azurin", "color": "#A9EAFE"},
    {"v": "Baillet (chevaux vieilli)", "color": "#AE642D"},
    {"v": "Banane", "color": "#D1B606"},
    {"v": "Basané (teint)", "color": "#8B6C42"},
    {"v": "Beige", "color": "#C8AD7F"},
    {"v": "Beige clair", "color": "#F5F5DC"},
    {"v": "Beigeasse (péjoratif)", "color": "#AFA77B"},
    {"v": "Beurre", "color": "#F0E36B"},
    {"v": "Beurre frais", "color": "#FFF48D"},
    {"v": "Bis", "color": "#766F64"},
    {"v": "Bis (héraldique)", "color": "#F1E2BE"},
    {"v": "Bisque", "color": "#FFE4C4"},
    {"v": "Bistre", "color": "#856D4D"},
    {"v": "Bitume", "color": "#4E3D28"},
    {"v": "Blanc", "color": "#FFFFFF"},
    {"v": "Blanc cassé", "color": "#FEFEE2"},
    {"v": "Blanc crème", "color": "#FDF1B8"},
    {"v": "Blanc d'argent (pigment)", "color": "#FEFEFE"},
    {"v": "Blanc d'Espagne (pigment)", "color": "#FEFDF0"},
    {"v": "Blanc de lait", "color": "#FBFCFA"},
    {"v": "Blanc de Meudon ou de Troyes (pigment)", "color": "#FEFDF0"},
    {"v": "Blanc de plomb ou Blanc-bleu (minéraux)", "color": "#FEFEFE"},
    {"v": "Blanc de zinc (pigment)", "color": "#F6FEFE"},
    {"v": "Blanc lunaire", "color": "#F4FEFE"},
    {"v": "Blé", "color": "#E8D630"},
    {"v": "Blet", "color": "#5B3C11"},
    {"v": "Bleu acier", "color": "#3A8EBA"},
    {"v": "Bleu ardoise", "color": "#686F8C"},
    {"v": "Bleu barbeau ou bleuet", "color": "#5472AE"},
    {"v": "Bleu canard", "color": "#048B9A"},
    {"v": "Bleu céleste", "color": "#26C4EC"},
    {"v": "Bleu céruléen", "color": "#357AB7"},
    {"v": "Bleu charrette", "color": "#8EA2C6"},
    {"v": "Bleu ciel", "color": "#77B5FE"},
    {"v": "Bleu de cobalt (pigment)", "color": "#22427C"},
    {"v": "Bleu de Berlin", "color": "#24445C"},
    {"v": "Bleu de France", "color": "#318CE7"},
    {"v": "Bleu de minuit", "color": "#003366"},
    {"v": "Bleu de Prusse (pigment)", "color": "#24445C"},
    {"v": "Bleu des mers du sud", "color": "#00CCCB"},
    {"v": "Bleu dragée", "color": "#DFF2FF"},
    {"v": "Bleu électrique", "color": "#2C75FF"},
    {"v": "Bleu fumée", "color": "#BBD2E1"},
    {"v": "Bleu givré", "color": "#80D0D0"},
    {"v": "Bleu guède", "color": "#56739A"},
    {"v": "Bleu hussard", "color": "#24445C"},
    {"v": "Bleu Klein", "color": "#002FA7"},
    {"v": "Bleu lavande", "color": "#9683EC"},
    {"v": "Bleu Majorelle", "color": "#6050DC"},
    {"v": "Bleu marine", "color": "#03224C"},
    {"v": "Bleu nuit", "color": "#0F056B"},
    {"v": "Bleu outremer", "color": "#1B019B"},
    {"v": "Bleu paon", "color": "#067790"},
    {"v": "Bleu Persan", "color": "#6600FF"},
    {"v": "Bleu pétrole", "color": "#1D4851"},
    {"v": "Bleu primaire", "color": "#0000FF"},
    {"v": "Bleu roi", "color": "#318CE7"},
    {"v": "Bleu saphir", "color": "#0131B4"},
    {"v": "Bleu turquin", "color": "#425B8A"},
    {"v": "Bleu turquoise", "color": "#25FDE9"},
    {"v": "Blond vénitien (cheveux)", "color": "#E7A854"},
    {"v": "Blond (cheveux)", "color": "#E2BC74"},
    {"v": "Bordeaux", "color": "#6D071A"},
    {"v": "Bourgogne", "color": "#6B0D0D"},
    {"v": "Bouton d'or", "color": "#FCDC12"},
    {"v": "Brique", "color": "#842E1B"},
    {"v": "Bronze", "color": "#614E1A"},
    {"v": "Brou de noix", "color": "#3F2204"},
    {"v": "Brun (cheveux)", "color": "#5B3C11"},
    {"v": "Brun clair (cheveux)", "color": "#CD853F"},
    {"v": "Bureau", "color": "#6B5731"},
    {"v": "Byzantin", "color": "#BD33A4"},
    {"v": "Byzantium", "color": "#702963"},
    {"v": "Caca d'oie", "color": "#CDCD0D"},
    {"v": "Cacao", "color": "#614B3A"},
    {"v": "Cachou", "color": "#2F1B0C"},
    {"v": "Cæruléum", "color": "#357AB7"},
    {"v": "Café", "color": "#462E01"},
    {"v": "Café au lait", "color": "#785E2F"},
    {"v": "Cannelle", "color": "#7E5835"},
    {"v": "Capucine", "color": "#FF5E4D"},
    {"v": "Caramel", "color": "#7E3300"},
    {"v": "Carmin", "color": "#960018"},
    {"v": "Carnation (héraldique) ou Carné (botanique)", "color": "#FEC3AC"},
    {"v": "Carotte", "color": "#F4661B"},
    {"v": "Cassis", "color": "#3A020D"},
    {"v": "Céladon", "color": "#83A697"},
    {"v": "Cerise", "color": "#DE3163"},
    {"v": "Céruse (pigment)", "color": "#FEFEFE"},
    {"v": "Chair", "color": "#FEC3AC"},
    {"v": "Chamois", "color": "#D0C07A"},
    {"v": "Champagne", "color": "#FBF2B7"},
    {"v": "Charbonneux", "color": "#000010"},
    {"v": "Chartreuse", "color": "#7FFF00"},
    {"v": "Châtaigne", "color": "#806D5A"},
    {"v": "Châtain (cheveux)", "color": "#8B6C42"},
    {"v": "Chaudron", "color": "#85530F"},
    {"v": "Chenu (cheveux)", "color": "#FEFEFE"},
    {"v": "Chocolat", "color": "#5A3A22"},
    {"v": "Cinabre", "color": "#DB1702"},
    {"v": "Citron", "color": "#F7FF3C"},
    {"v": "Citrouille", "color": "#DF6D14"},
    {"v": "Clarissimo (cigare)", "color": "#B9B276"},
    {"v": "Claro (cigare)", "color": "#845A3B"},
    {"v": "Claro claro (cigare)", "color": "#BA9B61"},
    {"v": "Colombin (vieilli)", "color": "#6A455D"},
    {"v": "Colorado (cigare)", "color": "#703516"},
    {"v": "Colorado claro (cigare)", "color": "#6A4B21"},
    {"v": "Coquelicot", "color": "#C60800"},
    {"v": "Coquille d'œuf", "color": "#FDE9E0"},
    {"v": "Corail", "color": "#E73E01"},
    {"v": "Cramoisi", "color": "#DC143C"},
    {"v": "Crème", "color": "#FDF1B8"},
    {"v": "Cuisse de nymphe", "color": "#FEE7F0"},
    {"v": "Cuisse de nymphe émue", "color": "#FF69B4"},
    {"v": "Cuivre", "color": "#B36700"},
    {"v": "Cyan", "color": "#2BFAFA"},
    {"v": "Cyan secondaire", "color": "#00FFFF"},
    {"v": "Denim", "color": "#1560BD"},
    {"v": "Dium (IPJ)", "color": "#0B1616"},
    {"v": "Ébène", "color": "#000000"},
    {"v": "Écarlate", "color": "#ED0000"},
    {"v": "Écru", "color": "#FEFEE0"},
    {"v": "Émeraude", "color": "#01D758"},
    {"v": "Étain oxydé", "color": "#BABABA"},
    {"v": "Étain pur", "color": "#EDEDED"},
    {"v": "Fauve", "color": "#AD4F09"},
    {"v": "Fer", "color": "#848484"},
    {"v": "Feu vif", "color": "#FF4901"},
    {"v": "Feuille morte", "color": "#99512B"},
    {"v": "Flave", "color": "#E6E697"},
    {"v": "Fleur de soufre", "color": "#FFFF6B"},
    {"v": "Fraise", "color": "#BF3030"},
    {"v": "Fraise écrasée", "color": "#A42424"},
    {"v": "Framboise", "color": "#C72C48"},
    {"v": "Fuchsia", "color": "#F400A1"},
    {"v": "Garance", "color": "#EE1010"},
    {"v": "Glauque", "color": "#649B88"},
    {"v": "Glycine", "color": "#C9A0DC"},
    {"v": "Grège", "color": "#BBAE98"},
    {"v": "Grenadine", "color": "#E9383F"},
    {"v": "Grenat", "color": "#6E0B14"},
    {"v": "Gris", "color": "#606060"},
    {"v": "Gris acier", "color": "#AFAFAF"},
    {"v": "Gris anthracite", "color": "#303030"},
    {"v": "Gris de lin", "color": "#D2CAEC"},
    {"v": "Gris de maure", "color": "#685E43"},
    {"v": "Gris de Payne", "color": "#677179"},
    {"v": "Gris fer", "color": "#7F7F7F"},
    {"v": "Gris fumée", "color": "#BBD2E1"},
    {"v": "Gris perle", "color": "#CECECE"},
    {"v": "Gris plomb", "color": "#798081"},
    {"v": "Gris souris", "color": "#9E9E9E"},
    {"v": "Gris taupe", "color": "#463F32"},
    {"v": "Gris tourdille (chevaux)", "color": "#C1BFB1"},
    {"v": "Gris tourterelle", "color": "#BBACAC"},
    {"v": "Groseille", "color": "#CF0A1D"},
    {"v": "Gueules (héraldique)", "color": "#E21313"},
    {"v": "Havane", "color": "#947F60"},
    {"v": "Héliotrope", "color": "#DF73FF"},
    {"v": "Hoto", "color": "#000000"},
    {"v": "Incarnadin", "color": "#FE96A0"},
    {"v": "Incarnat", "color": "#FF6F7D"},
    {"v": "Indigo chaud", "color": "#791CF8"},
    {"v": "Indigo du web", "color": "#4B0082"},
    {"v": "Indigo électrique", "color": "#6F00FF"},
    {"v": "Indigo (teinture)", "color": "#2E006C"},
    {"v": "Isabelle (chevaux)", "color": "#785E2F"},
    {"v": "Ivoire", "color": "#FFFFD4"},
    {"v": "Jade", "color": "#87E990"},
    {"v": "Jais", "color": "#000000"},
    {"v": "Jaune secondaire", "color": "#FFFF00"},
    {"v": "Jaune auréolin", "color": "#FDEE00"},
    {"v": "Jaune banane", "color": "#D1B606"},
    {"v": "Jaune bouton d’or", "color": "#F6DC12"},
    {"v": "Jaune canari", "color": "#E7F00D"},
    {"v": "Jaune chartreuse", "color": "#DFFF00"},
    {"v": "Jaune citron", "color": "#F7FF3C"},
    {"v": "Jaune d'or", "color": "#EFD807"},
    {"v": "Jaune de chrome (pigment)", "color": "#EDFF0C"},
    {"v": "Jaune de Mars", "color": "#EED153"},
    {"v": "Jaune de Naples (pigment)", "color": "#FFF0BC"},
    {"v": "Jaune fleur de soufre", "color": "#FFFF6B"},
    {"v": "Jaune impérial", "color": "#FFE436"},
    {"v": "Jaune maïs", "color": "#FFDE75"},
    {"v": "Jaune mimosa", "color": "#FEF86C"},
    {"v": "Jaune moutarde", "color": "#C7CF00"},
    {"v": "Jaune nankin", "color": "#F7E269"},
    {"v": "Jaune paille", "color": "#FEE347"},
    {"v": "Jaune poussin", "color": "#F7E35F"},
    {"v": "Jaune soufre", "color": "#FFFF6B"},
    {"v": "Kaki", "color": "#94812B"},
    {"v": "Lapis-lazuli", "color": "#26619C"},
    {"v": "Lavallière (reliure)", "color": "#8F5922"},
    {"v": "Lavande", "color": "#9683EC"},
    {"v": "Lie de vin", "color": "#AC1E44"},
    {"v": "Lilas", "color": "#B666D2"},
    {"v": "Lin", "color": "#FAF0E6"},
    {"v": "Maduro (cigare)", "color": "#372F25"},
    {"v": "Maduro colorado (cigare)", "color": "#5B3C11"},
    {"v": "Magenta fushia (encre)", "color": "#DB0073"},
    {"v": "Magenta secondaire", "color": "#FF00FF"},
    {"v": "Magenta foncé", "color": "#800080"},
    {"v": "Mauve", "color": "#965578"},
    {"v": "Maïs", "color": "#FFDE75"},
    {"v": "Malachite", "color": "#1FA055"},
    {"v": "Mandarine", "color": "#FEA347"},
    {"v": "Marine", "color": "#03224C"},
    {"v": "Marron", "color": "#582900"},
    {"v": "Mastic", "color": "#B3B191"},
    {"v": "Mauve", "color": "#D473D4"},
    {"v": "Melon", "color": "#DE9816"},
    {"v": "Menthe", "color": "#16B84E"},
    {"v": "Menthe à l'eau", "color": "#54F98D"},
    {"v": "Miel", "color": "#DAB30A"},
    {"v": "Mordoré", "color": "#87591A"},
    {"v": "Moreau (chevaux)", "color": "#000000"},
    {"v": "Moutarde", "color": "#C7CF00"},
    {"v": "Nacarat", "color": "#FC5D5D"},
    {"v": "Nankin", "color": "#F7E269"},
    {"v": "Neige", "color": "#FEFEFE"},
    {"v": "Noir", "color": "#000000"},
    {"v": "Noir animal", "color": "#000000"},
    {"v": "Noir charbon", "color": "#000010"},
    {"v": "Noir d'aniline", "color": "#120D16"},
    {"v": "Noir d'encre", "color": "#000000"},
    {"v": "Noir d'ivoire (pigment)", "color": "#000000"},
    {"v": "Noir de carbone (pigment)", "color": "#130E0A"},
    {"v": "Noir de fumée (pigment)", "color": "#130E0A"},
    {"v": "Noir de jais", "color": "#000000"},
    {"v": "Noiraud (teint, cheveux)", "color": "#2F1E0E"},
    {"v": "Noisette", "color": "#955628"},
    {"v": "Ocre jaune", "color": "#DFAF2C"},
    {"v": "Ocre rouge", "color": "#DD985C"},
    {"v": "Olive", "color": "#708D23"},
    {"v": "Opalin", "color": "#F2FFFF"},
    {"v": "Or", "color": "#FFD700"},
    {"v": "Orange", "color": "#ED7F10"},
    {"v": "Orange brûlée", "color": "#CC5500"},
    {"v": "Orchidée", "color": "#DA70D6"},
    {"v": "Orpiment", "color": "#FCD21C"},
    {"v": "Orpin de Perse", "color": "#FCD21C"},
    {"v": "Oscuro (cigare)", "color": "#292107"},
    {"v": "Paille", "color": "#FEE347"},
    {"v": "Papaye", "color": "#FFEFD5"},
    {"v": "Papier bulle", "color": "#EDD38C"},
    {"v": "Parme", "color": "#CFA0E9"},
    {"v": "Passe-velours", "color": "#91283B"},
    {"v": "Pastel", "color": "#56739A"},
    {"v": "Pêche", "color": "#FDBFB7"},
    {"v": "Pelure d'oignon (œnologie)", "color": "#D58490"},
    {"v": "Pervenche", "color": "#CCCCFF"},
    {"v": "Pinchard (chevaux vieilli)", "color": "#CCCCCC"},
    {"v": "Pistache", "color": "#BEF574"},
    {"v": "Platine", "color": "#FAF0C5"},
    {"v": "Plomb", "color": "#798081"},
    {"v": "Poil de chameau", "color": "#B67823"},
    {"v": "Ponceau", "color": "#C60800"},
    {"v": "Pourpre (héraldique)", "color": "#9E0E40"},
    {"v": "Prasin", "color": "#4CA66B"},
    {"v": "Prune", "color": "#811453"},
    {"v": "Puce", "color": "#4E1609"},
    {"v": "Queue-de-renard", "color": "#91283B"},
    {"v": "Queue-de-vache clair", "color": "#C3B470"},
    {"v": "Queue-de-vache foncé", "color": "#A89874"},
    {"v": "Réglisse", "color": "#2D241E"},
    {"v": "Rose", "color": "#FD6C9E"},
    {"v": "Rose balais (minéraux)", "color": "#C4698F"},
    {"v": "Rose bonbon", "color": "#F9429E"},
    {"v": "Rose dragée", "color": "#FEBFD2"},
    {"v": "Rose fuchsia", "color": "#FD3F92"},
    {"v": "Rose Mountbatten", "color": "#997A8D"},
    {"v": "Rose thé", "color": "#FF866A"},
    {"v": "Rose vif", "color": "#FF007F"},
    {"v": "Rouge Andrinople", "color": "#A91101"},
    {"v": "Rouge primaire", "color": "#FF0000"},
    {"v": "Rouge anglais", "color": "#F7230C"},
    {"v": "Rouge Bismarck", "color": "#A5260A"},
    {"v": "Rouge bordeaux", "color": "#6D071A"},
    {"v": "Rouge bourgogne", "color": "#6B0D0D"},
    {"v": "Rouge capucine", "color": "#FF5E4D"},
    {"v": "Rouge cardinal", "color": "#B82010"},
    {"v": "Rouge carmin", "color": "#960018"},
    {"v": "Rouge cerise", "color": "#BB0B0B"},
    {"v": "Rouge cinabre", "color": "#DB1702"},
    {"v": "Rouge coquelicot", "color": "#C60800"},
    {"v": "Rouge d'alizarine (pigment)", "color": "#E32636"},
    {"v": "Rouge d'Andrinople", "color": "#A91101"},
    {"v": "Rouge d'aniline", "color": "#ED0000"},
    {"v": "Rouge de Falun", "color": "#801818"},
    {"v": "Rouge de Mars (pigment)", "color": "#F7230C"},
    {"v": "Rouge écrevisse", "color": "#BC2001"},
    {"v": "Rouge feu", "color": "#FE1B00"},
    {"v": "Rouge fraise", "color": "#BF3030"},
    {"v": "Rouge framboise", "color": "#C72C48"},
    {"v": "Rouge grenadine", "color": "#E9383F"},
    {"v": "Rouge grenat", "color": "#6E0B14"},
    {"v": "Rouge Sokai", "color": "#920017"},
    {"v": "Rouge groseille", "color": "#CF0A1D"},
    {"v": "Rouge-violet", "color": "#C71585"},
    {"v": "Rouge ponceau", "color": "#C60800"},
    {"v": "Rouge sang", "color": "#850606"},
    {"v": "Rouge tomate", "color": "#DE2916"},
    {"v": "Rouge tomette", "color": "#AE4A34"},
    {"v": "Rouge turc", "color": "#A91101"},
    {"v": "Rouge vermillon", "color": "#DB1702"},
    {"v": "Rouille", "color": "#985717"},
    {"v": "Roux", "color": "#AD4F09"},
    {"v": "Rubis", "color": "#E0115F"},
    {"v": "Sable", "color": "#E0CDA9"},
    {"v": "Safran", "color": "#F3D617"},
    {"v": "Safre", "color": "#0131B4"},
    {"v": "Sang de bœuf", "color": "#730800"},
    {"v": "Sanguine (héraldique)", "color": "#850606"},
    {"v": "Saphir", "color": "#0131B4"},
    {"v": "Sarcelle", "color": "#008E8E"},
    {"v": "Saumon", "color": "#F88E55"},
    {"v": "Senois (héraldique)", "color": "#8D4024"},
    {"v": "Sépia", "color": "#AE8964"},
    {"v": "Sinople (héraldique)", "color": "#149414"},
    {"v": "Smalt", "color": "#003399"},
    {"v": "Smaragdin", "color": "#01D758"},
    {"v": "Soufre", "color": "#FFFF6B"},
    {"v": "Souris", "color": "#9E9E9E"},
    {"v": "Tabac", "color": "#9F551E"},
    {"v": "Tangerine (couleur)", "color": "#FF7F00"},
    {"v": "Tanné (héraldique)", "color": "#A75502"},
    {"v": "Taupe", "color": "#463F32"},
    {"v": "Terre d'ombre", "color": "#926D27"},
    {"v": "Terre de Sienne", "color": "#8A3324"},
    {"v": "Terre de Sienne brûlée", "color": "#E97451"},
    {"v": "Tilleuil", "color": "#4E1609"},
    {"v": "Tomate", "color": "#DE2916"},
    {"v": "Topaze", "color": "#FAEA73"},
    {"v": "Tourterelle", "color": "#BBACAC"},
    {"v": "Turquoise", "color": "#25FDE9"},
    {"v": "Vanille", "color": "#E1CE9A"},
    {"v": "Ventre de biche", "color": "#E9C9B1"},
    {"v": "Vermeil", "color": "#FF0921"},
    {"v": "Vermillon", "color": "#DB1702"},
    {"v": "Vert absinthe", "color": "#7FDD4C"},
    {"v": "Vert primaire", "color": "#00FF00"},
    {"v": "Vert amande", "color": "#82C46C"},
    {"v": "Vert anis", "color": "#9FE855"},
    {"v": "Vert avocat", "color": "#568203"},
    {"v": "Vert bouteille", "color": "#096A09"},
    {"v": "Vert céladon", "color": "#83A697"},
    {"v": "Vert chartreuse", "color": "#C2F732"},
    {"v": "Vert d'eau", "color": "#B0F2B6"},
    {"v": "Vert de chrome ou anglais (pigment)", "color": "#18391E"},
    {"v": "Vert-de-gris", "color": "#95A595"},
    {"v": "Vert de Hooker", "color": "#1B4F08"},
    {"v": "Vert de vessie", "color": "#22780F"},
    {"v": "Vert émeraude ou Smaragdin", "color": "#01D758"},
    {"v": "Vert épinard", "color": "#175732"},
    {"v": "Vert gazon ou herbe", "color": "#3A9D23"},
    {"v": "Vert impérial", "color": "#00561B"},
    {"v": "Vert jade", "color": "#87E990"},
    {"v": "Vert kaki", "color": "#798933"},
    {"v": "Vert lichen", "color": "#85C17E"},
    {"v": "Vert lime", "color": "#9EFD38"},
    {"v": "Vert malachite", "color": "#1FA055"},
    {"v": "Vert mélèze", "color": "#386F48"},
    {"v": "Vert menthe", "color": "#16B84E"},
    {"v": "Vert menthe à l'eau", "color": "#54F98D"},
    {"v": "Vert militaire", "color": "#596643"},
    {"v": "Vert mousse", "color": "#679F5A"},
    {"v": "Vert olive", "color": "#708D23"},
    {"v": "Vert opaline", "color": "#97DFC6"},
    {"v": "Vert perroquet", "color": "#3AF24B"},
    {"v": "Vert pin", "color": "#01796F"},
    {"v": "Vert pistache", "color": "#BEF574"},
    {"v": "Vert poireau ou prasin", "color": "#4CA66B"},
    {"v": "Vert pomme", "color": "#34C924"},
    {"v": "Vert prairie", "color": "#57D53B"},
    {"v": "Vert printemps", "color": "#00FF7F"},
    {"v": "Vert sapin", "color": "#095228"},
    {"v": "Vert sauge", "color": "#689D71"},
    {"v": "Vert tilleul", "color": "#A5D152"},
    {"v": "Vert turquoise", "color": "#1FFED8"},
    {"v": "Vert Véronèse (pigment)", "color": "#5A6521"},
    {"v": "Violet", "color": "#660099"},
    {"v": "Violet de Bayeux", "color": "#682145"},
    {"v": "Violet d'évêque", "color": "#723E64"},
    {"v": "Violine", "color": "#A10684"},
    {"v": "Viride", "color": "#40826D"},
    {"v": "Zinzolin", "color": "#6C0277"}
];