<?php
	sleep(2);
?>
<div class="page">
	<div class="w_bloc w_bg_light">
		This script automatically waits for 2 seconds before to respond.
		<br />
		<br />
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae convallis lorem. Duis sed ullamcorper ipsum. Cras consequat est quis lectus condimentum ac faucibus magna facilisis. In hac habitasse platea dictumst. Ut sed lectus lectus. Vestibulum vel nisi ac justo lobortis molestie. Pellentesque adipiscing fringilla neque, eu tincidunt erat sagittis nec. Donec accumsan dapibus tincidunt. Aenean non molestie risus. Morbi neque eros, egestas id vestibulum et, feugiat vel eros. Vestibulum dictum rhoncus est, et dictum justo porta in. Aliquam dapibus, diam at fermentum mollis, turpis nulla posuere dui, ac laoreet lacus felis eget sapien. Morbi nibh nisl, tempor consectetur consequat eu, iaculis tempus sem. Sed a lectus augue, ac porttitor odio. Nullam at est justo, ut auctor dui. Nunc lobortis leo quis felis sollicitudin semper. Curabitur venenatis lacus et enim venenatis hendrerit. Pellentesque sit amet velit ante, quis congue lacus.
		Curabitur cursus mattis sapien a mollis. Aenean vestibulum lacus pulvinar erat vehicula eu fermentum quam commodo. Morbi ut elit elit, at tincidunt ipsum. Nunc ante mi, ultricies ac facilisis id, tincidunt non nisl. Suspendisse luctus commodo sem, eu pharetra erat suscipit ornare. Mauris scelerisque ligula nec nulla interdum mollis. Proin id dolor felis, ut ultricies justo. Nulla vitae ante erat. Pellentesque bibendum nisi sed velit interdum dignissim. Phasellus et velit dui, ut venenatis orci. Donec volutpat quam a arcu rutrum mattis. Mauris iaculis, odio ut malesuada pellentesque, ante neque tincidunt dolor, eu malesuada erat est sed justo. Mauris malesuada scelerisque mauris vitae cursus. Aenean consequat turpis non eros varius rhoncus. Maecenas vitae leo libero, sed lobortis nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam ornare risus quis libero rhoncus quis auctor neque auctor.
		Praesent hendrerit egestas magna quis tincidunt. Nullam porttitor orci in quam bibendum sodales. Suspendisse mauris lacus, porttitor non iaculis at, molestie egestas neque. Sed viverra, lectus quis ultrices dapibus, arcu odio tempus magna, nec ullamcorper risus massa eget odio. Proin sagittis adipiscing metus, at aliquet erat ornare in. Ut ut commodo leo. Donec congue fermentum sem et placerat. Aliquam erat volutpat. Aliquam erat volutpat. Quisque tempor urna vel mi adipiscing quis aliquam risus posuere. Praesent at mauris felis. Quisque vestibulum ullamcorper felis, vel mollis felis pellentesque ut. Vestibulum convallis ornare dapibus. Fusce mollis pretium mi et sodales. Suspendisse quis lorem mauris, pulvinar fermentum purus.
		Duis iaculis auctor malesuada. Vestibulum euismod venenatis velit id commodo. Fusce ipsum arcu, tempor in accumsan ut, cursus non nibh. Curabitur quis vestibulum magna. Sed laoreet eros id lectus ornare semper. Curabitur sed diam urna. Ut vel imperdiet sapien. Mauris blandit eros et mi vestibulum a sodales erat tempus. Morbi aliquam tellus vulputate ipsum mollis sed lacinia metus facilisis. Donec id lectus vitae felis ultrices imperdiet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
		In commodo, turpis eu molestie condimentum, tortor sem cursus tellus, vitae egestas ligula mi ut augue. Nulla sed arcu tellus. Donec sem justo, tempor vel molestie nec, feugiat et est. Donec id ipsum urna, a tempor turpis. Maecenas vitae urna imperdiet neque vulputate ullamcorper nec non leo. Etiam vel tellus neque. Vestibulum fermentum nisl vel leo faucibus eu bibendum orci egestas. Cras id tempor erat. Duis id molestie tortor. Nulla eu nunc orci. Integer vitae venenatis augue.
		Nulla dictum mi quis est scelerisque dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus ultricies fermentum arcu, eget gravida eros lacinia ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in blandit sem. Proin posuere lacus posuere dui rhoncus gravida. Morbi vitae eros at libero vulputate eleifend eu in lectus. Pellentesque a lectus urna. Nullam vel velit lectus. Nullam vel sem nisl, non pulvinar justo. Donec tempor luctus tempus.
		Curabitur sit amet mauris non orci vulputate ultrices a nec metus. Vivamus molestie viverra tristique. Donec bibendum tempus ultricies. Donec semper, elit vel mattis pellentesque, velit elit varius quam, sit amet malesuada urna dui bibendum metus. Curabitur mattis, arcu ac dignissim fringilla, tellus ligula vestibulum massa, id egestas mi sem non sem. Proin nec justo sit amet mi hendrerit tincidunt. Donec et magna diam, id pharetra mi. Suspendisse a condimentum magna. Nullam gravida diam vitae velit tempor ultricies. Praesent elit dolor, aliquam in vehicula a, convallis ut lacus.
		Donec porttitor velit at dolor adipiscing id congue tellus imperdiet. Curabitur quis egestas lorem. Etiam urna mi, tincidunt aliquam porta quis, mattis et nunc. Fusce quis massa sed dolor suscipit fermentum. Aenean a dui at nisl placerat sollicitudin. Proin at nisl ut elit elementum venenatis. Vestibulum fermentum, sapien nec placerat tempus, magna mi molestie ipsum, eu laoreet leo dui id purus. Duis varius placerat placerat. Cras iaculis malesuada ultricies. Donec aliquam mattis elit, ac adipiscing nunc tempus non. Donec viverra, dui in faucibus molestie, odio lacus consectetur massa, suscipit dignissim elit massa sed sapien. Cras lacus urna, sollicitudin non tincidunt nec, gravida vitae odio. Nulla eu lacus mi. Suspendisse quis neque id neque tristique auctor quis a lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse orci mi, pulvinar at rhoncus a, luctus at justo. Nulla a diam nisl, non dignissim enim. Fusce eu tortor elementum eros consectetur aliquam. Donec quis arcu odio. Aliquam nec augue ante, eu accumsan lectus.
		Suspendisse vitae urna velit, id posuere lorem. In ac arcu a nibh ornare auctor a ut lorem. Phasellus a nunc urna. Suspendisse potenti. Morbi sit amet erat id mauris laoreet dictum. Nullam ultricies velit in sem interdum non vestibulum nulla blandit. Quisque elementum erat ac magna bibendum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac sem quis risus posuere volutpat eget ac urna. Nulla elementum malesuada justo non auctor. Nulla facilisi. Nunc et sapien arcu. Fusce sagittis quam a nisl tincidunt iaculis.
		Pellentesque interdum sapien et ipsum viverra commodo. In id magna sapien. Quisque pharetra dui malesuada leo posuere scelerisque. Morbi et orci lorem. Duis porta, quam in adipiscing congue, purus tortor sodales mauris, eu dignissim sapien tortor sit amet eros. Integer id mi velit, in venenatis sapien. Morbi elementum diam quis lectus lobortis vestibulum. Phasellus eget tellus vel erat blandit tempor in vel turpis. Sed aliquet vestibulum lacus, non ultrices arcu luctus id. Praesent feugiat aliquet neque quis accumsan. Aenean placerat, purus non dapibus vehicula, nunc mauris tempus mauris, a laoreet orci justo eget velit.
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vitae convallis lorem. Duis sed ullamcorper ipsum. Cras consequat est quis lectus condimentum ac faucibus magna facilisis. In hac habitasse platea dictumst. Ut sed lectus lectus. Vestibulum vel nisi ac justo lobortis molestie. Pellentesque adipiscing fringilla neque, eu tincidunt erat sagittis nec. Donec accumsan dapibus tincidunt. Aenean non molestie risus. Morbi neque eros, egestas id vestibulum et, feugiat vel eros. Vestibulum dictum rhoncus est, et dictum justo porta in. Aliquam dapibus, diam at fermentum mollis, turpis nulla posuere dui, ac laoreet lacus felis eget sapien. Morbi nibh nisl, tempor consectetur consequat eu, iaculis tempus sem. Sed a lectus augue, ac porttitor odio. Nullam at est justo, ut auctor dui. Nunc lobortis leo quis felis sollicitudin semper. Curabitur venenatis lacus et enim venenatis hendrerit. Pellentesque sit amet velit ante, quis congue lacus.
		Curabitur cursus mattis sapien a mollis. Aenean vestibulum lacus pulvinar erat vehicula eu fermentum quam commodo. Morbi ut elit elit, at tincidunt ipsum. Nunc ante mi, ultricies ac facilisis id, tincidunt non nisl. Suspendisse luctus commodo sem, eu pharetra erat suscipit ornare. Mauris scelerisque ligula nec nulla interdum mollis. Proin id dolor felis, ut ultricies justo. Nulla vitae ante erat. Pellentesque bibendum nisi sed velit interdum dignissim. Phasellus et velit dui, ut venenatis orci. Donec volutpat quam a arcu rutrum mattis. Mauris iaculis, odio ut malesuada pellentesque, ante neque tincidunt dolor, eu malesuada erat est sed justo. Mauris malesuada scelerisque mauris vitae cursus. Aenean consequat turpis non eros varius rhoncus. Maecenas vitae leo libero, sed lobortis nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam ornare risus quis libero rhoncus quis auctor neque auctor.
		Praesent hendrerit egestas magna quis tincidunt. Nullam porttitor orci in quam bibendum sodales. Suspendisse mauris lacus, porttitor non iaculis at, molestie egestas neque. Sed viverra, lectus quis ultrices dapibus, arcu odio tempus magna, nec ullamcorper risus massa eget odio. Proin sagittis adipiscing metus, at aliquet erat ornare in. Ut ut commodo leo. Donec congue fermentum sem et placerat. Aliquam erat volutpat. Aliquam erat volutpat. Quisque tempor urna vel mi adipiscing quis aliquam risus posuere. Praesent at mauris felis. Quisque vestibulum ullamcorper felis, vel mollis felis pellentesque ut. Vestibulum convallis ornare dapibus. Fusce mollis pretium mi et sodales. Suspendisse quis lorem mauris, pulvinar fermentum purus.
		Duis iaculis auctor malesuada. Vestibulum euismod venenatis velit id commodo. Fusce ipsum arcu, tempor in accumsan ut, cursus non nibh. Curabitur quis vestibulum magna. Sed laoreet eros id lectus ornare semper. Curabitur sed diam urna. Ut vel imperdiet sapien. Mauris blandit eros et mi vestibulum a sodales erat tempus. Morbi aliquam tellus vulputate ipsum mollis sed lacinia metus facilisis. Donec id lectus vitae felis ultrices imperdiet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
		In commodo, turpis eu molestie condimentum, tortor sem cursus tellus, vitae egestas ligula mi ut augue. Nulla sed arcu tellus. Donec sem justo, tempor vel molestie nec, feugiat et est. Donec id ipsum urna, a tempor turpis. Maecenas vitae urna imperdiet neque vulputate ullamcorper nec non leo. Etiam vel tellus neque. Vestibulum fermentum nisl vel leo faucibus eu bibendum orci egestas. Cras id tempor erat. Duis id molestie tortor. Nulla eu nunc orci. Integer vitae venenatis augue.
		Nulla dictum mi quis est scelerisque dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus ultricies fermentum arcu, eget gravida eros lacinia ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras in blandit sem. Proin posuere lacus posuere dui rhoncus gravida. Morbi vitae eros at libero vulputate eleifend eu in lectus. Pellentesque a lectus urna. Nullam vel velit lectus. Nullam vel sem nisl, non pulvinar justo. Donec tempor luctus tempus.
		Curabitur sit amet mauris non orci vulputate ultrices a nec metus. Vivamus molestie viverra tristique. Donec bibendum tempus ultricies. Donec semper, elit vel mattis pellentesque, velit elit varius quam, sit amet malesuada urna dui bibendum metus. Curabitur mattis, arcu ac dignissim fringilla, tellus ligula vestibulum massa, id egestas mi sem non sem. Proin nec justo sit amet mi hendrerit tincidunt. Donec et magna diam, id pharetra mi. Suspendisse a condimentum magna. Nullam gravida diam vitae velit tempor ultricies. Praesent elit dolor, aliquam in vehicula a, convallis ut lacus.
		Donec porttitor velit at dolor adipiscing id congue tellus imperdiet. Curabitur quis egestas lorem. Etiam urna mi, tincidunt aliquam porta quis, mattis et nunc. Fusce quis massa sed dolor suscipit fermentum. Aenean a dui at nisl placerat sollicitudin. Proin at nisl ut elit elementum venenatis. Vestibulum fermentum, sapien nec placerat tempus, magna mi molestie ipsum, eu laoreet leo dui id purus. Duis varius placerat placerat. Cras iaculis malesuada ultricies. Donec aliquam mattis elit, ac adipiscing nunc tempus non. Donec viverra, dui in faucibus molestie, odio lacus consectetur massa, suscipit dignissim elit massa sed sapien. Cras lacus urna, sollicitudin non tincidunt nec, gravida vitae odio. Nulla eu lacus mi. Suspendisse quis neque id neque tristique auctor quis a lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse orci mi, pulvinar at rhoncus a, luctus at justo. Nulla a diam nisl, non dignissim enim. Fusce eu tortor elementum eros consectetur aliquam. Donec quis arcu odio. Aliquam nec augue ante, eu accumsan lectus.
		Suspendisse vitae urna velit, id posuere lorem. In ac arcu a nibh ornare auctor a ut lorem. Phasellus a nunc urna. Suspendisse potenti. Morbi sit amet erat id mauris laoreet dictum. Nullam ultricies velit in sem interdum non vestibulum nulla blandit. Quisque elementum erat ac magna bibendum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac sem quis risus posuere volutpat eget ac urna. Nulla elementum malesuada justo non auctor. Nulla facilisi. Nunc et sapien arcu. Fusce sagittis quam a nisl tincidunt iaculis.
		Pellentesque interdum sapien et ipsum viverra commodo. In id magna sapien. Quisque pharetra dui malesuada leo posuere scelerisque. Morbi et orci lorem. Duis porta, quam in adipiscing congue, purus tortor sodales mauris, eu dignissim sapien tortor sit amet eros. Integer id mi velit, in venenatis sapien. Morbi elementum diam quis lectus lobortis vestibulum. Phasellus eget tellus vel erat blandit tempor in vel turpis. Sed aliquet vestibulum lacus, non ultrices arcu luctus id. Praesent feugiat aliquet neque quis accumsan. Aenean placerat, purus non dapibus vehicula, nunc mauris tempus mauris, a laoreet orci justo eget velit. 
	</div>
</div>
