var winkloader=function(){var e={winkPath:"",moduleConf:null,profileConf:null,moduleFile:null,profileFile:null,profile:"default",target:null,callback:null},r={conf:e,load:function(b){var d=b.profileConf;if(!b.moduleConf||!d)throw Error("missing parameter");if(d=b.winkPath)e.winkPath=d;if(d=b.callback)e.callback=d;if(d=b.profile)e.profile=d;if(d=b.target)e.target=d;e.moduleFile=b.moduleConf;e.profileFile=b.profileConf;p=document.getElementsByTagName("head")[0];if(e.target==null)e.target=r.detectTarget();
if(e.moduleConf==null)e.moduleConf=u(e.moduleFile);if(e.profileConf==null)e.profileConf=u(e.profileFile);b=e.target;d=[];var a=e.profileConf,g=a.implementations;a=s(a.profiles,e.profile).modules;var f,i=a.length;for(f=0;f<i;f++){var l=a[f],h=l;if(g){var j,k=g.length;for(j=0;j<k;j++){var o=g[j];if(o.module==l){h=o.defaultImpl;l=o.subImpls;k=l.length;for(j=0;j<k;j++){o=l[j];if(o.target==b)h=o.impl}break}}}d.push(h)}b=[];g=e.moduleConf.modules;f=d.length;for(a=0;a<f;a++){i=[];q(g,d[a],i);l=i.length;
for(h=0;h<l;h++){subj=i[h];j=false;o=b.length;for(k=0;k<o;k++)if(b[k]==subj){j=true;break}j||b.push(subj)}}d=e.target;g=[];a=e.moduleConf.modules;f=e.winkPath;i=s(e.profileConf.profiles,e.profile);h=[];h=e.profileConf.build.defaultLocaleList;i=h=(i=i.localeList)&&i.length>0?i:h;l=b.length;for(h=0;h<l;h++){k=t(a,b[h]);g.push(f+k.defaultImpl);j=m(k,i);if(o=k.subImpls){var v,x=o.length;for(v=0;v<x;v++){k=o[v];if(k.target==d){o=m(k,i);if(k.excludeDefault==true){g.pop();j=[]}g.push(f+k.impl);j=j.concat(o);
break}}}g=g.concat(j)}w.load(g,e.callback)},setMethods:function(b){n=b;delete this.setMethods}},p,n,q=function(b,d,a){var g=t(b,d).modules;if(g){var f=g.length;for(d=0;d<f;d++)q(b,g[d],a)}else a.push(d)},m=function(b,d){var a=[],g=e.winkPath;if(b.i18n&&b.i18n.length>0){var f,i=b.i18n.length;for(f=0;f<i;f++){var l=b.i18n[f],h,j=d.length;for(h=0;h<j;h++){var k=l[d[h]];k&&a.push(g+k)}}}return a},s=function(b,d){var a,g=b.length;for(a=0;a<g;a++){var f=b[a];if(f.name==d)return f}return null},t=function(b,
d){var a,g=b.length;for(a=0;a<g;a++){var f=b[a];if(f.name==d)return f}return null},w=function(){var b={load:function(l,h){d=l;g=h;a=-1;f=0;i()},markAsLoaded:function(){i()},markAsError:function(){f++;markAsLoaded()}},d=null,a=null,g=null,f=null,i=function(){a++;if(a==d.length){if(f>0)throw Error("Some files cannot be loaded ("+f+")");g!=null&&g()}a>=d.length||n(p,d[a],b.markAsLoaded,b.markAsError)};return b}(),u=function(b){var d=null,a;a=null;var g="";if(typeof XMLHttpRequest!=="undefined")a=new XMLHttpRequest;
if(!a){var f=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],i,l=f.length;for(i=0;i<l;i++){var h=f[i];try{a=new ActiveXObject(h);break}catch(j){g=j}}}if(!a)throw Error("_getXhr - XMLHttpRequest not available : "+g);a=a;a.open("GET",b,false);a.send(null);if(a.readyState==4)if(a.status>=200&&a.status<400||a.status==0)d=a.responseText;else throw Error("unable to retrieve url '"+b+"' : "+a.statusText);eval("var c = "+d);return c};return r}();
(function(e){e.detectTarget=function(){var r="default",p=navigator||{},n=p.userAgent,q=p.platform;p=p.appVersion;n={webkit:/ AppleWebKit\//.test(n),ios:RegExp(/iphone/i).test(q)||RegExp(/ipod/i).test(q)||RegExp(/ipad/i).test(q),android:RegExp(/android/i).test(p),opera:RegExp(/Opera/gi).test(n),blackberry:RegExp(/blackberry/i).test(q),bada:RegExp(/bada/gi).test(n),firefox:RegExp(/firefox/i).test(n),ie:RegExp(/MSIE/i).test(n)};if(!n.webkit&&n.ie)r="ie";return r};e.setMethods(function(r,p,n,q){var m=
document.createElement("script");m.type="text/javascript";if(m.addEventListener){var s=function(){m.removeEventListener("load",s,false);m.removeEventListener("error",t,false);n()},t=function(){m.removeEventListener("load",s,false);m.removeEventListener("error",t,false);q()};m.addEventListener("load",s,false);m.addEventListener("error",t,false)}else{var w=function(u){if(/^(complete|loaded)$/.test((u.currentTarget||u.srcElement).readyState)){m.detachEvent("onreadystatechange",w);n()}};m.attachEvent("onreadystatechange",
w)}m.src=p;r.appendChild(m)})})(winkloader);
